apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: {{ .Values.smtp.host }}
      smtp_from: {{ .Values.smtp.from }}
      smtp_auth_username: {{ .Values.smtp.username }}
      smtp_auth_password: {{ .Values.smtp.password }}
      smtp_require_tls: true
    receivers:
      - name: 'email_notifications'
        email_configs:
          - to: {{ .Values.receiverEmail }}
            send_resolved: true
    route:
      receiver: 'email_notifications'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 24h
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: {{ .Values.replicaCounts.alertmanager }}
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: {{ .Values.images.alertmanager }}
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: {{ .Values.nodePorts.alertmanager }}
