# templates/test-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: django-test-job2
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 db 3306; do echo "Waiting for database connection..."; sleep 5; done']
      containers:
      - name: django
        image: "{{ .Values.images.web }}:{{ .Values.images.tag2 }}"
        command: ["python", "manage.py", "fetch_year_data"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: tech_demo.settings
        - name: DATABASE_URL
          value: mysql://sayali97:Sugandha1274*@db:3306/stock_data
      restartPolicy: OnFailure
