apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'stock_metrics'
        metrics_path: '/api/stock-price-metrics/'
        static_configs:
          - targets: ['web:8000']
    rule_files:
      - 'alerts.yml'
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - 'alertmanager:9093'
  alerts.yml: |
    groups:
      - name: stock_alerts
        rules:
          - alert: StockPriceChange
            expr: abs(stock_price_change_percentage) > 5
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Stock price change alert"
              description: "The stock price has changed by more than 5%."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: {{ .Values.replicaCounts.prometheus }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.images.prometheus }}
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.nodePorts.prometheus }}
