apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: {{ .Values.replicaCounts.web }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: {{ .Values.images.web }}
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: tech_demo.settings
        - name: DATABASE_URL
          value: mysql://{{ .Values.mysql.user }}:{{ .Values.mysql.password }}@db:3306/{{ .Values.mysql.database }}
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.nodePorts.web }}
